#!/bin/bash

DOCKER_CLI=`(which docker)`
DOCKERIM_CACHE_FILE="$HOME/.dockerim"

function saveId {
    echo -n "$CURRENT_CONTAINER_ID" > $DOCKERIM_CACHE_FILE
}

if [ -e $DOCKERIM_CACHE_FILE ]; then
    CURRENT_CONTAINER_ID=`(cat $DOCKERIM_CACHE_FILE)`
fi

case "$1" in
    "bash")
        if [ -z "$2" ]; then
            $DOCKER_CLI exec -it $CURRENT_CONTAINER_ID bash
        else
            $DOCKER_CLI exec -it "$2" bash
        fi
        exit 0
        ;;
    "set")
        if [ "$2" -ge 0 -a "$2" -le 9 ]; then
            export CURRENT_CONTAINER_ID=`docker ps -q | sed -n $(($2+1))p`
        else
            export CURRENT_CONTAINER_ID="$2"
        fi

        echo $CURRENT_CONTAINER_ID
        saveId
        exit 0
        ;;
    "unset")
        export CURRENT_CONTAINER_ID=""
        saveId
        exit 0
        ;;
    "logs"|"kill"|"rm")
        if [ -z "$2" ]; then
            set -- "$1" "$CURRENT_CONTAINER_ID"
        fi
        ;;
    "run")
        export CURRENT_CONTAINER_ID=`$DOCKER_CLI "$@"`
        echo $CURRENT_CONTAINER_ID
        saveId
        exit 0
        ;;
    "killall")
        $DOCKER_CLI kill `($DOCKER_CLI ps -q)`
        exit 0
        ;;
    "rmall")
        $DOCKER_CLI rm `($DOCKER_CLI ps -q -a)`
        exit 0
        ;;
    "current")
        if [ ! -z $CURRENT_CONTAINER_ID ]; then
            echo $CURRENT_CONTAINER_ID
        fi
        exit 0
        ;;
    "help" | "")
        $DOCKER_CLI help
        echo
        echo -e "dockerim (v0.1) commands:"
        echo -e "    set <id|index>\tSets current container"
        echo -e "    unset\t\tClears current container"
        echo -e "    logs\t\tPrint current container logs"
        echo -e "    kill/rm\t\tKills/Remove current container"
        echo -e "    killall/rmall\tKills/Removes ALL containers"
        echo -e "    current\t\tPrints current container id"
        echo
        echo -e "Otherwise, dockerim will pass the command as is to docker CLI"
        echo
        echo
        exit 0
        ;;
esac

# Pass command to docker CLI if no special handling require
$DOCKER_CLI "$@"

