#!/bin/bash

DOCKER_CLI=`(which docker)`
DOCKERIM_CACHE_FILE="$HOME/.dockerim"

function saveId {
    echo "$CURRENT_CONTAINER_ID" > $DOCKERIM_CACHE_FILE
}

if [ -e $DOCKERIM_CACHE_FILE ]; then
    CURRENT_CONTAINER_ID=`(cat $DOCKERIM_CACHE_FILE)`
fi

case "$1" in
    "bash")
        if [ -z "$2" ]; then
            $DOCKER_CLI exec -it $CURRENT_CONTAINER_ID bash
        else
            $DOCKER_CLI exec -it "$2" bash
        fi
        exit 0
        ;;
    "set")
        if [ "$2" -ge 0 -a "$2" -le 9 ]; then
            export CURRENT_CONTAINER_ID=`docker ps -q | sed -n $(($2+1))p`
        else
            export CURRENT_CONTAINER_ID="$2"
        fi

        echo $CURRENT_CONTAINER_ID
        saveId
        exit 0
        ;;
    "unset")
        export CURRENT_CONTAINER_ID=""
        saveId
        exit 0
        ;;
    "logs"|"kill")
        if [ -z "$2" ]; then
            set -- "$1" "$CURRENT_CONTAINER_ID"
        fi
        ;;
    "run")
        export CURRENT_CONTAINER_ID=`$DOCKER_CLI "$@"`
        echo $CURRENT_CONTAINER_ID
        saveId
        exit 0
        ;;
    "killall")
        $DOCKER_CLI kill `($DOCKER_CLI ps -q)`
        exit 0
        ;;
    "rmall")
        $DOCKER_CLI rm `($DOCKER_CLI ps -q -a)`
        exit 0
        ;;
    "current")
        if [ -z $CURRENT_CONTAINER_ID ]; then
            echo "No current container. use 'docker set <num|id>' or 'docker run ...' to set"
        else
            echo $CURRENT_CONTAINER_ID
        fi
        exit 0
        ;;
    "help" | "")
        echo "dockerim: docker IMproved (v0.1)"
        echo
        echo "Usage:"
        echo "   dockerim set <ps index | container id> / docker run ..."
        echo "       Sets current container. ex: 'docker set 0' will set the current container to the first one on PS"
        echo
        echo "   dockerim unset"
        echo "       Clears current container"
        echo
        echo "   dockerim logs/kill"
        echo "       If run without a container ID, will use the current container"
        echo
        echo "   dockerim killall/rmall"
        echo "       Will kill/remove all containers"
        echo
        echo "   dockerim current"
        echo "       Will print the current container id"
        echo
        echo "Otherwise, this command will pass the command as is to docker CLI"
        echo
        echo
        ;;
esac

# Pass command to docker CLI if no special handling require
$DOCKER_CLI "$@"

